<!DOCTYPE html>
<html lang="fr-FR">
    <head>
        <title>Home</title>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width height=device-height">
        <meta name="theme-color" content="#fff">
        <link rel="shortcut icon" href="img/favicon.ico"></link>
        <link rel="icon" type="image/png" href="img/favicon.png" sizes="16x16" />
        <link href='//fonts.googleapis.com/css?family=Oswald' rel='stylesheet' type='text/css'>
        <style>
            .container {min-width:300px;max-width:1200px;margin:auto;font-family: sans-serif;}
            .container h2{text-align: center; color:#27748A;font-size:25px;margin:0;box-shadow: 5px 5px 5px #888888;padding:20px;border:4px solid #27748A;}
            .container p{font-size:15px;color:#222222;}
            .container div{margin-top:10px;}
            .container input, textarea, button{ margin: 2px; /*border:2px solid #9ECEDB;*/padding:3px 5px;}
            .container activite{ margin: 5px;}
            .container #prix{ width: 40px; padding:3px 5px;}
            .container button{border:2px solid #9ECEDB;}
            .container label{font-weight:bold;font-size:12px;color:#184552;}
            .container button{background-color: #9ECEDB;color: #184552;cursor:pointer;}
            .container button:hover{background-color: #CBEAF2;}
            .required{color:#dd6666;}
            .validation-message{margin: 5px 0px; padding:5px; border: 1px solid; border-radius:.5em; box-shadow:1px 1px 3px #888; color: #D8000C; background-color: #FFBABA;font-size: 10px;}

            .interacted:invalid {border: 1px solid red;}
            .interacted:valid {border: 1px solid green;}

            /* modal */
            .modal { display: none; position: fixed; top: 0; right: 0; bottom: 0; left: 0; padding: 15px; overflow: auto; background-color: rgba(0, 0, 0, 0.88); -webkit-animation-duration: 0.35s; animation-duration: 0.35s; -webkit-animation-fill-mode: both; animation-fill-mode: both; -webkit-animation-name: fadeIn; animation-name: fadeIn; }
            .modal__dialog { position: relative; max-width: 500px; padding: 20px; margin: auto; border-radius: 4px; background-color: #fff; }
            .modal__close { position: absolute; top: 20px; right: 20px; padding: 0; border: none; color: #ccc; background-color: transparent; background-image: none; }
            .modal__close:focus { outline: 0; }
            .modal__header { border-bottom: 1px solid #e2e2e2; }
            .modal__title { margin: 0 0 15px; }
            .modal__content { padding: 10px 0; font-size: 13px; line-height: 1.6; color: #555; }
            .modal__footer { padding-top: 20px; border-top: 1px solid #e2e2e2; text-align: right; }
            .modal--fullscreen { padding: 5px; }
            .modal--fullscreen .modal__dialog { width: 100%; max-width: none; height: 100%; border-radius: 0;}
            .modal.is-modal-active { display: -webkit-box; display: -ms-flexbox; display: flex;}
            .modal button:not(.modal__close){border:2px solid #9ECEDB;}
            .modal button:not(.modal__close){background-color: #9ECEDB;color: #184552;cursor:pointer;}
            .modal button:hover:not(.modal__close){background-color: #CBEAF2;}

            /* Animation */
            @-webkit-keyframes fadeIn {0% {opacity: 0;} 100% {opacity: 1;}}
            @keyframes fadeIn {0% {opacity: 0;}100% {opacity: 1;}}

            /* spinner */
            .spinner { display: none; width: 100px; height: 100px; margin: 100px 120px; background-color: #333; border-radius: 100%; -webkit-animation: sk-scaleout 1.0s infinite ease-in-out; animation: sk-scaleout 1.0s infinite ease-in-out; z-index: 10; position: absolute; text-align: center;}
            @-webkit-keyframes sk-scaleout { 0% { -webkit-transform: scale(0) } 100% { -webkit-transform: scale(1.0); opacity: 0;}}
            @keyframes sk-scaleout { 0% { -webkit-transform: scale(0); transform: scale(0); } 100% { -webkit-transform: scale(1.0); transform: scale(1.0); opacity: 0;} }

            /* spinner action */
            .spinner-action {position: absolute; display: none; margin: 2px auto; width: 50px; height: 40px; text-align: center; font-size: 10px; padding: 3px 5px;}
            .spinner-action > div {background-color: #9ECEDB; height: 100%; width: 6px; display: inline-block; -webkit-animation: sk-stretchdelay 1.2s infinite ease-in-out; animation: sk-stretchdelay 1.2s infinite ease-in-out; margin: 0 3px 0 0;}
            .spinner-action .rect2 {-webkit-animation-delay: -1.1s; animation-delay: -1.1s; }
            .spinner-action .rect3 {-webkit-animation-delay: -1.0s; animation-delay: -1.0s;}
            .spinner-action .rect4 { -webkit-animation-delay: -0.9s; animation-delay: -0.9s;}
            .spinner-action .rect5 { -webkit-animation-delay: -0.8s; animation-delay: -0.8s;}
            @-webkit-keyframes sk-stretchdelay { 0%, 40%, 100% { -webkit-transform: scaleY(0.4) } 20% { -webkit-transform: scaleY(1.0) }}
            @keyframes sk-stretchdelay { 0%, 40%, 100% { transform: scaleY(0.4); -webkit-transform: scaleY(0.4);}  20% { transform: scaleY(1.0); -webkit-transform: scaleY(1.0);}}

            body select { padding: 5px 30px 5px 10px !important; max-width: 100%; height: auto !important; border: 1px solid #e3e3e3; border-radius: 3px; background: url("https://image.ibb.co/iMeAJv/selectbox_arrow.png") right center no-repeat; background-color: #fff; color: #444444; font-size: 12px; line-height: 16px !important; appearance: none; /* this is must */ -webkit-appearance: none; -moz-appearance: none; } 
            body select option { padding: 0 4px; }
        </style>
    </head>
    <body>
        <div class="container">
            <h2>
                <a href="https://asml-montesson.jimdo.com/" style="border: 0; text-decoration: none; cursor: pointer;" name="logobanner">
                    <img class="myFlexedImage" src="https://u.jimcdn.com/cms/o/s0b7da5ead516c378/emotion/crop/header.jpg?t=1481845558" id="emotion-header-img" alt="Logo Banner">
                </a><br /> 
                BULLETIN INSCRIPTION 2017 / 2018
            </h2>
        </div>
        <!-- GA -->
        <script>
            (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
                m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
            })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

            ga('create', '<?= $uidGA?>', 'auto');
            ga('send', 'pageview');
        </script>
    </body>
</html>
