<!DOCTYPE html>
<html lang="fr-FR">
    <head>
        <title>Formulaire d'inscription ASML</title>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width height=device-height">
        <meta name="theme-color" content="#fff">
        <link rel="shortcut icon" href="img/favicon.ico"></link>
        <link rel="icon" type="image/png" href="img/favicon.png" sizes="16x16" />
        <link href='//fonts.googleapis.com/css?family=Oswald' rel='stylesheet' type='text/css'>
        <style>
            .container {min-width:300px;max-width:1200px;margin:auto;font-family: sans-serif;}
            .container h2{text-align: center; color:#27748A;font-size:25px;margin:0;box-shadow: 5px 5px 5px #888888;padding:20px;border:4px solid #27748A;}
            .container p{font-size:15px;color:#222222;}
            .container div{margin-top:10px;}
            .container input, textarea, button{ margin: 2px; /*border:2px solid #9ECEDB;*/padding:3px 5px;}
            .container activite{ margin: 5px;}
            .container #prix{ width: 40px; padding:3px 5px;}
            .container button{border:2px solid #9ECEDB;}
            .container label{font-weight:bold;font-size:12px;color:#184552;}
            .container button{background-color: #9ECEDB;color: #184552;cursor:pointer;}
            .container button:hover{background-color: #CBEAF2;}
            .required{color:#dd6666;}
            .validation-message{margin: 5px 0px; padding:5px; border: 1px solid; border-radius:.5em; box-shadow:1px 1px 3px #888; color: #D8000C; background-color: #FFBABA;font-size: 10px;}

            .interacted:invalid {border: 1px solid red;}
            .interacted:valid {border: 1px solid green;}

            .myFlexedImage {margin: auto; padding: 0; max-width:100%; 
                display: -webkit-flex; display: flex; flex-flow: row;
                -webkit-flex-direction: row; flex-direction: row;
                -webkit-justify-content: center; justify-content: center;
                -webkit-align-items: center; align-items: center;
                -webkit-align-self: center; align-self: center;
            }

            #step1 {min-height: 400px; margin: 0; padding: 0; 
                display: -webkit-flex; display: flex; flex-flow: row;
                -webkit-flex-direction: row; flex-direction: row;
                -webkit-justify-content: center; justify-content: center;
                -webkit-align-items: stretch; align-items: stretch;}
            #step2, #step3, #step4 {min-height: 400px; margin: 0; padding: 0; 
                display: -webkit-flex; display: flex; flex-flow: column;
                -webkit-flex-direction: column; flex-direction: column;
                -webkit-justify-content: flex-start; justify-content: flex-start;
                -webkit-align-items: stretch; align-items: stretch;}
            #step1 > maindata {margin: 4px;padding: 5px;
                 /*border: 1px solid #cccc33;border-radius: 7pt;background: #dddd88;*/
                -webkit-flex: 2 1 40%; flex: 2 1 35%;
                -webkit-order:0; order: 0;}    
            #step1 > subdata {margin: 4px;padding: 5px;
                 /*border: 1px solid #cccc33;border-radius: 7pt;background: #dddd88;*/
                -webkit-flex: 2 1 40%; flex: 2 1 35%;
                -webkit-order:1; order: 1;
                -webkit-align-self: strech; align-self: strech;}    
            #step1 > photo {margin: 4px;padding: 5px;
                width: 200px; min-height: 200px; max-width: 400px;
                border: 1px solid #cccc33;border-radius: 7pt;
                /*border: 1px solid #cccc33;border-radius: 7pt;background: #dddd88;*/
                -webkit-flex: 1 6 20%; flex: 1 6 30%;
                -webkit-order: 2; order: 2;
                -webkit-align-self: flex-start; align-self: flex-start;
                display:-webkit-flex;display:flex;flex-flow: column;} 
            #step1 > maindata input { width:100%;box-sizing : border-box;}
            #step1 > subdata input:not([type='radio']) { width:100%;box-sizing : border-box;}
            #signature {flex-flow: row; -webkit-flex-direction: row; flex-direction: row;}
            #signature .nomsignature{width: 200px;}

            #nav {min-height: 50px; margin: 0; padding: 0; 
                display: -webkit-flex; display: flex; flex-flow: row;
                -webkit-flex-direction: row; flex-direction: row;
                -webkit-justify-content: center; justify-content: center;
                -webkit-align-items: center; align-items: center;}

            disclaimer { margin: 4px;}      
            #commentaire, #inscrfamillename, #payeurnom {width: 100%;}
            #pinscrfamillename {display: none;}

            #preview {background-color:#fff;width:200px;}
            .cheque_montant{margin: 5px;}

            headerstep2, 
            headerstep3, 
            headerstep4 {display: none; margin: 4px; padding: 5px; min-height: 50px;}

            headerstep1, 
            footer {display: -webkit-flex; display: flex; margin: 4px; padding: 5px; min-height: 50px;}

            .textup {text-transform: uppercase;}

            /* Too narrow to support three columns */
            @media all and (max-width: 640px) {
                #step1, #step2, #step3, #step4 {flex-direction: column;}
                headerstep1, headerstep2, headerstep3, headerstep4, footer {min-height: 50px;max-height: 50px;}
                #step1 > photo, #step1 > maindata, #step1 > subdata {order: 0;}
            }

            /* modal */
            .modal { display: none; position: fixed; top: 0; right: 0; bottom: 0; left: 0; padding: 15px; overflow: auto; background-color: rgba(0, 0, 0, 0.88); -webkit-animation-duration: 0.35s; animation-duration: 0.35s; -webkit-animation-fill-mode: both; animation-fill-mode: both; -webkit-animation-name: fadeIn; animation-name: fadeIn; }
            .modal__dialog { position: relative; max-width: 500px; padding: 20px; margin: auto; border-radius: 4px; background-color: #fff; }
            .modal__close { position: absolute; top: 20px; right: 20px; padding: 0; border: none; color: #ccc; background-color: transparent; background-image: none; }
            .modal__close:focus { outline: 0; }
            .modal__header { border-bottom: 1px solid #e2e2e2; }
            .modal__title { margin: 0 0 15px; }
            .modal__content { padding: 10px 0; font-size: 13px; line-height: 1.6; color: #555; }
            .modal__footer { padding-top: 20px; border-top: 1px solid #e2e2e2; text-align: right; }
            .modal--fullscreen { padding: 5px; }
            .modal--fullscreen .modal__dialog { width: 100%; max-width: none; height: 100%; border-radius: 0;}
            .modal.is-modal-active { display: -webkit-box; display: -ms-flexbox; display: flex;}
            .modal button:not(.modal__close){border:2px solid #9ECEDB;}
            .modal button:not(.modal__close){background-color: #9ECEDB;color: #184552;cursor:pointer;}
            .modal button:hover:not(.modal__close){background-color: #CBEAF2;}

            /* Animation */
            @-webkit-keyframes fadeIn {0% {opacity: 0;} 100% {opacity: 1;}}
            @keyframes fadeIn {0% {opacity: 0;}100% {opacity: 1;}}

            /* spinner */
            .spinner { display: none; width: 100px; height: 100px; margin: 100px 120px; background-color: #333; border-radius: 100%; -webkit-animation: sk-scaleout 1.0s infinite ease-in-out; animation: sk-scaleout 1.0s infinite ease-in-out; z-index: 10; position: absolute; text-align: center;}
            @-webkit-keyframes sk-scaleout { 0% { -webkit-transform: scale(0) } 100% { -webkit-transform: scale(1.0); opacity: 0;}}
            @keyframes sk-scaleout { 0% { -webkit-transform: scale(0); transform: scale(0); } 100% { -webkit-transform: scale(1.0); transform: scale(1.0); opacity: 0;} }

            /* spinner action */
            .spinner-action {position: absolute; display: none; margin: 2px auto; width: 50px; height: 40px; text-align: center; font-size: 10px; padding: 3px 5px;}
            .spinner-action > div {background-color: #9ECEDB; height: 100%; width: 6px; display: inline-block; -webkit-animation: sk-stretchdelay 1.2s infinite ease-in-out; animation: sk-stretchdelay 1.2s infinite ease-in-out; margin: 0 3px 0 0;}
            .spinner-action .rect2 {-webkit-animation-delay: -1.1s; animation-delay: -1.1s; }
            .spinner-action .rect3 {-webkit-animation-delay: -1.0s; animation-delay: -1.0s;}
            .spinner-action .rect4 { -webkit-animation-delay: -0.9s; animation-delay: -0.9s;}
            .spinner-action .rect5 { -webkit-animation-delay: -0.8s; animation-delay: -0.8s;}
            @-webkit-keyframes sk-stretchdelay { 0%, 40%, 100% { -webkit-transform: scaleY(0.4) } 20% { -webkit-transform: scaleY(1.0) }}
            @keyframes sk-stretchdelay { 0%, 40%, 100% { transform: scaleY(0.4); -webkit-transform: scaleY(0.4);}  20% { transform: scaleY(1.0); -webkit-transform: scaleY(1.0);}}

            body select { padding: 5px 30px 5px 10px !important; max-width: 100%; height: auto !important; border: 1px solid #e3e3e3; border-radius: 3px; background: url("https://image.ibb.co/iMeAJv/selectbox_arrow.png") right center no-repeat; background-color: #fff; color: #444444; font-size: 12px; line-height: 16px !important; appearance: none; /* this is must */ -webkit-appearance: none; -moz-appearance: none; } 
            body select option { padding: 0 4px; }
        </style>
    </head>
    <body>
        <div class="container">
            <h2>
                <a href="https://asml-montesson.jimdo.com/" style="border: 0; text-decoration: none; cursor: pointer;" name="logobanner">
                    <img class="myFlexedImage" src="https://u.jimcdn.com/cms/o/s0b7da5ead516c378/emotion/crop/header.jpg?t=1481845558" id="emotion-header-img" alt="Logo Banner">
                </a><br /> 
                BULLETIN INSCRIPTION 2017 / 2018
            </h2>
            <headerstep1><p><span>Coordonnées</span> (1 bulletin par adhérent)</p></headerstep1>
            <headerstep2><p><span>Activité(s) choisie(s)</span> (maximum 3)</p></headerstep2>
            <headerstep3><p><span>Réglement</span> à l’ordre de L’ASML (obligatoire pour valider l’inscription)</p></headerstep3>
            <headerstep4><p><span>Merci pour votre inscription</span></p></headerstep4>
            <form id="form1">
                <div id="step1">
                    <photo>
                        <div class="spinner" id="spinner" ></div>
                        <img id="preview" alt=""/>
                        <div>
                            <label id="photolabel" for="photo">Selectionnez votre photo (maximum 1Mo)</label>
                            <input type="file" id="photo" accept="image/*" onchange="displayUpload();"/>
                            <button id="uploadPhoto" style="display: none;" > Charger la photo </button> 
                        </div>
                    </photo>
                    <maindata>
                        <div>
                            <label for='email'>Email <span class='required'>(*)</span></label>
                            <input type='email' name='email' id='email' placeholder='you@yourdomain.com' required />
                        </div>
                        <div>
                            <label for='nom'>Nom <span class='required'>(*)</span></label>
                            <input type='text' class="textup" name='nom' placeholder="Nom de l'adhérent" required />
                        </div>
                        <div>
                            <label for='prenom'>Prénom <span class='required'>(*)</span></label>
                            <input type='text' class="textup" name='prenom' placeholder="Prénom de l'adhérent" required />
                        </div>
                        <div>
                            <label for='birthdate'>Date de naissance <span class='required'>(*)</span></label>
                            <input type='date' name='birthdate' required max="2013-12-01" />
                        </div>
                        <div>
                            <label for='telfixe'>Téléphone</label>
                            <input type='tel' name='telfixe' placeholder='Télèphone fixe' />
                        </div>
                        <div>
                            <label for='tel'>Portable</label>
                            <input type='tel' name='tel' placeholder='Télèphone portable' />
                        </div>
                    </maindata>
                    <subdata>
                        <div>
                            <label for='adresse'>Adresse <span class='required'>(*)</span></label>
                            <input type='text' name='adresse' placeholder="Adresse " required />
                        </div>
                        <div>
                            <label for='ville'>Ville</label>
                            <input type="text" name='ville' placeholder="Ville" required />
                        </div>
                        <div>
                            <label for='codepostal'>Code Postal</label>
                            <input type="text" pattern ="[0-9]{5}" name='codepostal' placeholder="Code postal" required />
                        </div>
                        <div>
                            <label for='adherentprec'>Adhérent année précédente</label>
                            <input type='checkbox' name='adherentprec' id="adherentprec"/>
                        </div>
                        <div>
                            <label for='nationalite'>Nationalité</label>
                            <input type="text" name='nationalite' placeholder="Nationalité"/>
                        </div>
                        <div>
                            <label for="sexe">Sexe</label>
                            <input type='radio' name='sexe' value="F" required >F
                            <input type='radio' name='sexe' value="M">M
                        </div>
                    </subdata>
                </div>
        <?= $this->formElement($form->get('ctok')); ?>
            </form>
            <form id="form2">
                <div id="step2" style="display: none;">
                    <activite>
                        <label for='section1'>Choix N°1 <span class='required'>(*)</span></label>
                        <select id='section1' name="section[1]" required>
                            <option />
                            <option value='Enfants/Ados'>Enfants / ados</option>
                            <option value='Adultes'>Adultes</option>
                            <option value='Seniors'>Seniors</option>
                        </select>
                        <select id='activite' name="activite[1]" required>
                        </select>
                        <select id='day' name='day[1]' required>
                        </select>
                        <input type='text' id='prix' name='prix[1]' placeholder="Prix " disabled/>€
                    </activite>
                    <div id="button-step2">
                        <button id="addactivity" style="display: flex;">Ajouter une activité</button>
                    </div>
                    <disclaimer>
                        Aucune remise ne pourra être déduite sans tampon du Bureau
                        Les remises ou avoirs ne seront accordés que pour les dossiers complets.
                        Les conditions d'application des remises sont consultables <a href="<?=$rebateConditions?>">ici</a>  
                    </disclaimer>
                    <annexes>
                        <div>
                            <label for="commentaire"><p>Commentaires <span>(contraintes médicales …)</span></p></label>
                            <textarea name='commentaire' id="commentaire"></textarea>
                        </div>

                        <div>
                            <label for="documentreglement">Demande (joindre enveloppe supplémentaire, timbrée à votre adresse)</label>
                            <input type='checkbox' name='attestation' value=1 />Attestation
                            <input type='checkbox' name='facture' value=1 />Facture
                        </div>
                    </annexes>
                </div>
                <?= $this->formElement($form->get('ctok')); ?>
            </form>
            <form id="form3">
                <div id="step3" style="display: none;">
                    <div id="payeur">
                        <label for='payeurnom'>Nom et prénom du payeur <span class='required'>(*)</span></label>
                        <input type='text' class="textup" id="payeurnom" name='payeurnom' placeholder="Nom et prénom du payeur" required />
                    </div>
                    <div id="methodpayment">
                        <p class="disclaimer">merci de ne pas antidater les chèques. Pour rappel, le montant de vos inscriptions est de <span class="euros" id="montant_total"></span>€</p>
                        <div>
                            <input type='radio' name='cheque' value=1 id='paiement1' required />
                            <label for="check1">1 chèque en Novembre </label>
                        </div>
                        <div id='cheque_1' style="display: none;">
                            <div class="cheque_montant" >
                                <label for="cheque_novembre">Montant Novembre </label>
                                <input type="text" name="cheque_novembre" id="cheque_novembre_1" required />€
                            </div>
                        </div>
                        <div>
                            <input type='radio' name='cheque' value=2 id='paiement2' />
                            <label for="cheque_2">2 chèques en Novembre et Janvier</label>
                        </div>
                        <div id='cheque_2' style="display: none;">
                            <div class="cheque_montant" >
                                <label for="cheque_novembre">Montant Novembre </label>
                                <input type="text" name="cheque_novembre" id="cheque_novembre_2" required />€
                            </div>
                            <div class="cheque_montant" >
                                <label for="cheque_janvier">Montant Janvier </label>
                                <input type="text" name="cheque_janvier" id="cheque_janvier_2" />€
                            </div>
                        </div>
                        <div>
                            <input type='radio' name='cheque' value=3 id='paiement3' />
                            <label for="check3">3 chèques en Novembre, Janvier et Avril</label>
                        </div>
                        <div id='cheque_3' style="display: none;">
                             <div class="cheque_montant" >
                                <label for="cheque_novembre">Montant Novembre </label>
                                <input type="text" name="cheque_novembre" id="cheque_novembre_3" required />€
                            </div>
                            <div class="cheque_montant" >
                                <label for="cheque_janvier">Montant Janvier </label>
                                <input type="text" name="cheque_janvier" id="cheque_janvier_3" />€
                            </div>
                            <div class="cheque_montant" >
                                <label for="cheque_avril">Montant Avril </label>
                                <input type="text" name="cheque_avril" id="cheque_avril_3" />€
                            </div>
                        </div>
                        <div>
                            <input type='checkbox' name='cheque_ancv' value=4 id='ancv' />
                            <label for="cheque_ancv">ANCV (chèque Vacances ou coupon Sport)</label>
                            <span id="s_montantancv" style="display: none;" >
                                <input type='text' id='montantancv' name='montantancv' placeholder="Montant chèque ANCV" pattern ="[0-9]{3}" />€
                            </span>
                        </div>
                    </div>
                </div>
                <?= $this->formElement($form->get('ctok')); ?>
            </form>
            <form id="form4" method="post" action="">
                <div id="step4" style="display: none;">
                    <div id="signature">
                    Je soussigné(e), <input type='text' class="textup" id='nomsignature' name='nomsignature' placeholder="Nom et prénom" required /> déclare avoir pris connaissance de la charte ASML (au verso et sur le site) et en accepter les termes.
                    </div>
                    <div id="inscrfamillebox" name="inscrfamillebox">
                        <label for="inscrfamille">Inscription Famille?</label>
                        <input type='checkbox' name='inscrfamille' id="inscrfamille" value=1 />
                        <p id="pinscrfamillename">
                            <label for="inscrfamillename">Nom de l’autre adhérent : </label>
                            <input type='text' class="textup" id="inscrfamillename" name='inscrfamillename' placeholder="Saisir le nom et le prénom de l'autre adhérent" />
                        </p>
                    </div>
                </div>
                <?= $this->formElement($form->get('ctok')); ?>
            </form>
            <div id="inscriptionfinie" style="display: none;">
                <p>
                    <span>les documents à remettre sont disponibles via les liens ci dessous :</span>
                    <ul>
                        <li>
                            <a href="https://asml-montesson.jimdo.com/app/download/9111246985/Bulletin+INSCRIPTION+ASML+2017-2018.pdf?t=1497531244">
                                <span>Bulletin inscription 2017-2018<span>
                            </a>
                        </li>
                        <li>
                            <a href="https://asml-montesson.jimdo.com/app/download/8675544085/Licence+pratiquant+2017-2018.pdf?t=1497531244">
                                <span>LICENCE PRATIQUANT 2017-2018 à signer recto et verso<span>
                            </a>
                        </li>
                        <li>
                            <a href="https://asml-montesson.jimdo.com/app/download/8675598385/licence+famille+2017-2018.pdf?t=1497531244">
                                <span>LICENCE FAMILLE à signer et remplir en 3 exemplaires<span>
                            </a>
                        </li>
                        <li>
                            <a href="https://asml-montesson.jimdo.com/app/download/9140823985/questionnaire+sant%C3%A9+2017+a+signer.pdf?t=1497531244">
                                <span>Pour les adhérents 2016-2017 ayant fourni un certificat médical daté de septembre 2016<span>
                            </a>
                        </li>
                    </ul>
                </p>
            </div>
            <div id="nav">
                <button id="prev-step" type="submit" style="display: none;" > Precedent </button>
                <button id="next-step" type="submit" style="display: flex;"> Suivant </button>
                <button id="submit" type="submit" class="g-recaptcha" style="display: none;" data-sitekey="<?=$googleCaptcha?>" data-callback="captchaFeedback"> Enregistrer </button>
                <div class="spinner-action" id="spinner-action">
                    <div class="rect1"></div>
                    <div class="rect2"></div>
                    <div class="rect3"></div>
                    <div class="rect4"></div>
                    <div class="rect5"></div>
                </div>
            </div>
        </div>
        <!-- new inscr modal -->
        <div class="modal" data-modal-name="step-confirm-modal">
            <div class="modal__dialog">
                <button class="modal__close" data-modal-dismiss>×</button>
                <header class="modal__header">
                    <h3 class="modal__title">Souhaitez vous inscrire un autre membre?</h3>
                </header>
                <div class="modal__content">
                    <p>Si vous souhaitez inscrire une autre personne de suite, veuillez cliquer sur <strong>Oui</strong> ci dessous.</p>
                    <p>Si vous souhaitez finir votre inscription, il suffit pour cela de cliquer sur <strong>Non</strong> ci dessous.</p>
                </div>
                <footer class="modal__footer">
                    <button data-modal-confirm class="modal__btn">Oui, inscrire un autre membre</button>
                    <button data-modal-dismiss class="modal__btn">Non, finir mon inscription</button>
                </footer>
            </div>
        </div>
        <script src='https://www.google.com/recaptcha/api.js'></script>
        <!-- GA -->
        <script>
            (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
                m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
            })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

            ga('create', '<?= $uidGA?>', 'auto');
            ga('send', 'pageview');
        </script>
        <script>
            var closeBut = '<button class="closing" id="closing" >X</button>',
                elementNext = document.getElementById("next-step"),
                elementPrev = document.getElementById("prev-step"),
                div1 = document.getElementById("step1"),
                div2 = document.getElementById("step2"),
                div3 = document.getElementById("step3"),
                div4 = document.getElementById("step4"),
                header1 = document.getElementsByTagName("headerstep1")[0],
                header2 = document.getElementsByTagName("headerstep2")[0],
                header3 = document.getElementsByTagName("headerstep3")[0],
                header4 = document.getElementsByTagName("headerstep4")[0],
                iMaxFilesize = 1048576, // 1MB
                formVars = {},
                startPos = 1,
                _dismiss = document.querySelectorAll('[data-modal-dismiss]'),
                _confirm = document.querySelectorAll('[data-modal-confirm]'),
                _targettedModal,
                modalActiveClass = "is-modal-active";

            document.addEventListener('DOMContentLoaded', function() {
                var forms = document.querySelectorAll('form');
                for (var index = forms.length - 1; index >= 0; index--) {
                    var form = forms[index];
                    form.noValidate = true;
                }
            });

            var validateForm = function(submitEvent, form) {

                var elements = form.elements;

                if (!form.checkValidity()) {
                    /* Seriously, hold everything. */
                    submitEvent.preventDefault();
                    submitEvent.stopImmediatePropagation();
                    submitEvent.stopPropagation();
                    for (var index = 0, len = elements.length; index < len; index++) {
                        var element = elements[index];
                        if (element.parentNode.getElementsByClassName('validation-message').length > 0) {

                            element.parentNode.removeChild(element.parentNode.getElementsByClassName('validation-message')[0]);
                        }

                        if (element.willValidate === true && element.validity.valid !== true) {
                            var message = 'Ce champ est obligatoire - veuillez le remplir ou verifier le format', // element.validationMessage,
                                parent  = element.parentNode,
                                div     = document.createElement('div');
                            div.appendChild(document.createTextNode(message));
                            div.classList.add('validation-message');
                            parent.insertBefore(div, element.nextSibling);
                            element.focus();
                            break;
                        }
                    }
                } else {
                    return true;
                }
            };

            document.getElementById("addactivity").addEventListener("click", function(e) {

                e.preventDefault();
                var activites = document.getElementsByTagName('activite');
                var itm = activites[0],
                    butDiv = document.getElementById('button-step2');
                var cln = itm.cloneNode(true);
                cln.innerHTML += closeBut;
                var newPos = activites.length+1,
                    pctRebate = 30;
                if (newPos>2) {

                    pctRebate = 40;
                }
                cln.innerHTML += '<div id="rebate"><span>remise de '+pctRebate+'%</span><div>';
                cln.innerHTML = cln.innerHTML.replace("N°1", "N°"+newPos).replace(/section1/g, 'section'+newPos).replace(/section\[1\]/g, 'section['+newPos+']').replace(/activite\[1\]/g, 'activite['+newPos+']').replace(/day\[1\]/g, 'day['+newPos+']').replace(/prix\[1\]/g, 'prix['+newPos+']');
                document.getElementById("step2").insertBefore(cln, butDiv);
                cln.querySelector('#section'+newPos).addEventListener("change", bindActivities);
                var daySelect = cln.querySelector('#day');
                for(i = daySelect.options.length - 1 ; i >= 0 ; i--) {
                    daySelect.remove(i);
                }
                cln.querySelector('button').addEventListener("click", function(event) {
                    event.preventDefault();
                    this.parentNode.parentNode.removeChild(this.parentNode);
                    var activites = document.getElementsByTagName('activite');
                    if (activites.length < 3) {

                        document.getElementById("addactivity").style.display = 'flex';
                    }
                });
                if (activites.length >= 3) {

                    document.getElementById("addactivity").style.display = 'none';
                }
            });
            document.getElementById('inscrfamille').addEventListener("click", function(e) {

                if (document.getElementById('inscrfamille').checked) {
                    document.getElementById('pinscrfamillename').style.display = 'flex';
                } else {
                    document.getElementById('pinscrfamillename').style.display = 'none';
                }
            });
            document.getElementById("next-step").addEventListener("click", function(e) {

                e.preventDefault();
                errorMessages = document.getElementsByClassName('validation-message');
                for (var index = 0, len = errorMessages.length; index < len; index++) {

                    var element = errorMessages[index];
                    element.parentNode.removeChild(element);
                }
                if (div1.style.display != 'none') {

                    if (document.forms['form1'].checkValidity()) {

                        for ( var i = 0; i < document.forms['form1'].elements.length; i++ ) {

                            var e = document.forms['form1'].elements[i];
                            if (e.disabled == 'undefined' || e.disabled == false) {

                                formVars[ e.name ] = e.value;
                            }
                        }
                        if (false!==saveData('step1', startPos, formVars)) {

                            div1.style.display = 'none';
                            div2.style.display = 'flex';
                            div3.style.display = 'none';
                            div4.style.display = 'none';
                            header1.style.display = 'none';
                            header2.style.display = 'flex';
                            header3.style.display = 'none';
                            header4.style.display = 'none';
                        } else {
                            return;
                        }
                    } else {

                        return validateForm(e, document.forms['form1']);
                    }
                } else if (div2.style.display != 'none') {

                    if (document.forms['form2'].checkValidity()) {

                        for ( var i = 0; i < document.forms['form2'].elements.length; i++ ) {

                            var e = document.forms['form2'].elements[i];
                            if (e.disabled == 'undefined' || e.disabled == false) {

                                formVars[ e.name ] = e.value;
                            }
                        }
                        var prices = document.querySelectorAll('#prix');
                        if (startPos==1) {
                            
                            formVars['montant_total'] = 0;
                        }
                        for (var index = prices.length - 1; index >= 0; index--) {
                            rebateFactor = 1;
                            if (index==2) {

                                rebateFactor = 0.6;
                            }
                            if (index==1) {
                                rebateFactor = 0.7;
                            }
                            formVars[ 'montant_total' ] += Math.floor(parseInt(prices[index].value)*rebateFactor);
                        }
                        if(false!==saveData('step2', startPos, formVars)) {

                            showModal('step-confirm-modal');
                        } else {

                            return;
                        }
                    } else {

                        return validateForm(e, document.forms['form2']);
                    }
                } else {
                    
                    if (document.forms['form3'].checkValidity()) {
                        
                        for ( var i = 0; i < document.forms['form3'].elements.length; i++ ) {
                            var e = document.forms['form3'].elements[i];
                            if (e.disabled == 'undefined' || e.disabled == false) {

                                formVars[ e.name ] = e.value;
                            }
                        }
                        if (false!==saveData('step3', startPos, formVars)) {

                            div1.style.display = 'none';
                            div2.style.display = 'none';
                            div3.style.display = 'none';
                            div4.style.display = 'flex';
                            header1.style.display = 'none';
                            header2.style.display = 'none';
                            header3.style.display = 'none';
                            header4.style.display = 'flex';

                            document.getElementById('inscrfamillebox').style.display = 'bloc'; 
                            if (startPos>1) {

                                document.getElementById('inscrfamillebox').style.display = 'none'; 
                            }
                        }else{

                            return;
                        }
                    } else {

                        return validateForm(e, document.forms['form3']);
                    }
                }
                if (div1.style.display != 'none')
                    elementPrev.style.display = 'none';
                else
                    elementPrev.style.display = 'flex';
                if (div4.style.display != 'none') {
                    elementNext.style.display = 'none';
                    document.getElementById("submit").style.display = 'flex';    
                } else
                    elementNext.style.display = 'flex';
            });
            document.getElementById("prev-step").addEventListener("click", function(e) {

                e.preventDefault();
                var elementNext = document.getElementById("next-step"),
                    elementPrev = document.getElementById("prev-step"),
                    div4 = document.getElementById("step4"),
                    div3 = document.getElementById("step3"),
                    div2 = document.getElementById("step2"),
                    div1 = document.getElementById("step1"),
                    header1 = document.getElementsByTagName("headerstep1")[0],
                    header2 = document.getElementsByTagName("headerstep2")[0],
                    header3 = document.getElementsByTagName("headerstep3")[0],
                    header4 = document.getElementsByTagName("headerstep4")[0];

                if (div4.style.display != 'none') {

                    if (false !== cleanData('step3', startPos)) {

                        div1.style.display = 'none';
                        div2.style.display = 'none';
                        div3.style.display = 'flex';
                        div4.style.display = 'none';
                        header1.style.display = 'none';
                        header2.style.display = 'none';
                        header3.style.display = 'flex';
                        header4.style.display = 'none';
                    }else{

                        return;
                    }
                } else if ( div3.style.display != 'none') {

                    if (false!==cleanData('step2', startPos)) {

                        div1.style.display = 'none';
                        div2.style.display = 'flex';
                        div3.style.display = 'none';
                        div4.style.display = 'none';
                        header1.style.display = 'none';
                        header2.style.display = 'flex';
                        header3.style.display = 'none';
                        header4.style.display = 'none';
                    }else{

                        return;
                    }

                } else {

                    if(false!==cleanData('step1', startPos)){

                        div1.style.display = 'flex';
                        div2.style.display = 'none';
                        div3.style.display = 'none';
                        div4.style.display = 'none';
                        header1.style.display = 'flex';
                        header2.style.display = 'none';
                        header3.style.display = 'none';
                        header4.style.display = 'none';
                    }else{

                        return;
                    }
                }
                if (div1.style.display != 'none')
                    elementPrev.style.display = 'none';
                else
                    elementPrev.style.display = 'flex';
                if (div4.style.display != 'none') {
                    elementNext.style.display = 'none';
                    document.getElementById("submit").style.display = 'flex';    
                } else {
                    elementNext.style.display = 'flex';
                    document.getElementById("submit").style.display = 'none'; 
                }
            });
            document.getElementById("submit").addEventListener("click", function(e) {

                e.preventDefault();
                var element = document.getElementById("next-step");
                if (element.style.display != 'none')
                    element.style.display = 'none';

                if (document.forms['form4'].checkValidity()) {

                    elementNext.style.display = 'none';
                    elementPrev.style.display = 'none';
                    document.getElementById("submit").style.display = 'none';
                    document.getElementById('spinner-action').style.display = 'flex';

                    //console.log(formVars);
                    //saveData('step4', startPos, formVars);
                } else {
                    if (e.target.id=='prev-step') {

                        return;
                    }
                    return validateForm(e, document.forms['form4']);
                }
            });
            document.getElementById('section1').addEventListener("change", bindActivities);

            function captchaFeedback(token) {

                grecaptcha.execute();
                var xhr = new XMLHttpRequest();
                xhr.open('POST', '<?=$this->url('asml/savedata')?>',false);
                xhr.setRequestHeader('Content-Type', 'application/json');
                xhr.onload = function() {
                    if (xhr.status === 200) {

                        document.getElementById('step4').style.display = 'none';
                        document.getElementById('spinner-action').style.display = 'none';
                        document.getElementById('nav').style.display = 'none';
                        document.getElementById('inscriptionfinie').style.display = 'flex';
                    }
                }
                xhr.send(JSON.stringify({'currentStep': 'step4', 'currentPos': startPos, 'formData': formVars}));
            }

            function bindActivities(event) {
                var selectActivity = this.parentNode.querySelectorAll('#activite')[0];
                var xhr = new XMLHttpRequest();
                xhr.open('POST', '<?=$this->url('asml/sections')?>');
                xhr.setRequestHeader('Content-Type', 'application/json');
                xhr.onload = function() {
                    if (xhr.status === 200) {
                        var activityInfo = JSON.parse(xhr.responseText);
                        var opt = document.createElement('option');
                        for(i = selectActivity.options.length - 1 ; i >= 0 ; i--) {
                            selectActivity.remove(i);
                        }
                        selectActivity.appendChild(opt);
                        for (optKey in activityInfo) {

                            var opt = document.createElement('option');
                            opt.value = activityInfo[optKey].value;
                            opt.innerHTML = activityInfo[optKey].html;
                            selectActivity.appendChild(opt);
                        }
                        selectActivity.addEventListener("change", function(e) {
                            var selectDay = this.parentNode.querySelectorAll('#day')[0]
                                ,prixActivite = this.parentNode.querySelectorAll('#prix')[0];
                            var xhr = new XMLHttpRequest();
                            xhr.open('POST', '<?=$this->url('asml/activities')?>');
                            xhr.setRequestHeader('Content-Type', 'application/json');
                            xhr.onload = function() {
                                if (xhr.status === 200) {
                                    var dayInfo = JSON.parse(xhr.responseText);
                                    var opt = document.createElement('option');
                                    for(i = selectDay.options.length - 1 ; i >= 0 ; i--) {
                                        selectDay.remove(i);
                                    }
                                    selectDay.appendChild(opt);
                                    prixActivite.value = dayInfo[0].prix;
                                    for (optKey in dayInfo) {

                                        var opt = document.createElement('option');
                                        opt.value = dayInfo[optKey].value;
                                        opt.innerHTML = dayInfo[optKey].html;
                                        selectDay.appendChild(opt);
                                    }
                                }
                            }
                            xhr.send(JSON.stringify({'activite': this.value}));
                        });
                    }
                }
                xhr.send(JSON.stringify({'section': this.value}));
            }

            function displayUpload() {
                var oFile = document.getElementById('photo').files[0];
                if (oFile.size > iMaxFilesize) {
                    return;
                }
                document.getElementById('uploadPhoto').style.display = 'flex'; 
                document.getElementById('photo').style.display = 'none'; 
                document.getElementById('photolabel').style.display = 'none'; 

                var oImage = document.getElementById('preview');
                var oReader = new FileReader();
                oReader.onload = function(e){
                    oImage.src = e.target.result;    
                }
                oReader.readAsDataURL(oFile);

                document.getElementById('uploadPhoto').addEventListener("click", function(e) {
                    e.preventDefault();
                    document.getElementById('spinner').style.display = 'flex';
                    document.getElementById('uploadPhoto').style.display = 'none'; 

                    var oFile = document.getElementById('photo').files[0];
                    var vFD = new FormData();
                    vFD.append('photo', oFile);
                    vFD.append('email', document.getElementById('email').value);
                    var oXHR = new XMLHttpRequest();
                    oXHR.open('POST', '<?=$this->url('asml/uploadphoto')?>');
                    oXHR.onload = function() {
                        if (oXHR.status === 200) {
                            var photoInfo = JSON.parse(oXHR.responseText);
                            if (photoInfo.error) {

                                return;
                            }
                            formVars['photo'] = photoInfo.localPath;
                        }
                        document.getElementById('spinner').style.display = 'none';
                    }
                    oXHR.send(vFD);
                });
            }

            function replaceValidationUI( form ) {
                // Suppress the default bubbles
                form.addEventListener( "invalid", function( event ) {
                    event.preventDefault();
                }, true );

                // Support Safari, iOS Safari, and the Android browser—each of which do not prevent
                // form submissions by default
                form.addEventListener( "submit", function( event ) {
                    if ( !this.checkValidity() ) {
                        event.preventDefault();
                    }
                });

                var submitButton = document.querySelector( "#prev-step, #next-step, #submit" );
                submitButton.addEventListener( "click", function( event ) {
                    if (event.target.id=="prev-step") {

                        return;
                    }
                    var invalidFields = form.querySelectorAll( ":invalid" ),
                        errorMessages = form.querySelectorAll( ".error-message" ),
                        parent;

                    // Remove any existing messages
                    for ( var i = 0; i < errorMessages.length; i++ ) {
                        errorMessages[ i ].parentNode.removeChild( errorMessages[ i ] );
                    }
    
                    for ( var i = 0; i < invalidFields.length; i++ ) {
                        parent = invalidFields[ i ].parentNode;
                        parent.insertAdjacentHTML( "beforeend", "<div class='error-message'>" + 
                            invalidFields[ i ].validationMessage +
                            "</div>" );
                    }

                    // If there are errors, give focus to the first invalid field
                    if ( invalidFields.length > 0 ) {
                        invalidFields[ 0 ].focus();
                    }
                });
            }

            // Replace the validation UI for all forms
            var forms = document.querySelectorAll( "form" );
            for ( var i = 0; i < forms.length; i++ ) {
                replaceValidationUI( forms[ i ] );
            }

            function saveData(currentStep, currentPos, formData)
            {
                var returnCode = true,
                    currentDispNext = elementNext.style.display,
                    currentDispPrev = elementPrev.style.display,
                    currentDispSub = document.getElementById("submit").style.display;

                elementNext.style.display = 'none';
                elementPrev.style.display = 'none';
                document.getElementById("submit").style.display = 'none';
                document.getElementById('spinner-action').style.display = 'flex';
                var xhr = new XMLHttpRequest();
                xhr.open('POST', '<?=$this->url('asml/savedata')?>', false);
                xhr.setRequestHeader('Content-Type', 'application/json');
                xhr.onload = function() {
                    if (xhr.status !== 200) {

                        console.log('unable to save data'); 
                        returnCode=false;
                    }
                    document.getElementById('spinner-action').style.display = 'none';
                    elementNext.style.display = currentDispNext;
                    elementPrev.style.display = currentDispPrev;
                    document.getElementById("submit").style.display = currentDispSub;
                    return returnCode;
                }
                xhr.send(JSON.stringify({'currentStep': currentStep, 'currentPos': currentPos, 'formData': formData}));
            }

            function cleanData(currentStep, currentPos)
            {
                var xhr = new XMLHttpRequest();
                xhr.open('POST', '<?=$this->url('asml/deletedata')?>', false);
                xhr.setRequestHeader('Content-Type', 'application/json');
                xhr.onload = function() {
                    if (xhr.status !== 200) {
                        console.log('unable to clean data'); 
                        return false;
                    }
                    return true;
                }
                xhr.send(JSON.stringify({'currentStep': currentStep, 'currentPos': currentPos}));
            }

            function bindEvents(el, callback){
                for (i = 0; i < el.length; i++) {
                    (function(i) {
                        el[i].addEventListener('click', function(event) {
                            callback(this, event);
                        });
                    })(i);
                } 
            }

            function showModal(el){

                _targettedModal = document.querySelector('[data-modal-name="'+ el + '"]');
                _targettedModal.classList.add(modalActiveClass);
                bindEvents(_dismiss, function(that){
                    hideModal(event);
                    showStep3();
                });
                bindEvents(_confirm, function(that){
                    hideModal(event);
                    showNewStep1();
                });
            }

            function hideModal(event){

                if(event === undefined || event.target.hasAttribute('data-modal-dismiss')
                    || event.target.hasAttribute('data-modal-confirm')) {

                    _targettedModal.classList.remove(modalActiveClass);
                }
            }

            function showNewStep1() {

                startPos = startPos + 1;

                document.forms['form1'].reset();
                document.forms['form2'].reset();
                document.forms['form3'].reset();

                document.getElementById('preview').src='';
                document.getElementById('uploadPhoto').style.display = 'none'; 
                document.getElementById('photo').style.display = 'flex'; 
                document.getElementById('photolabel').style.display = 'flex'; 

                div1.style.display = 'flex';
                div2.style.display = 'none';
                div3.style.display = 'none';
                div4.style.display = 'none';
                header1.style.display = 'flex';
                header2.style.display = 'none';
                header3.style.display = 'none';
                header4.style.display = 'none';
            }

            function showStep3() {

                div1.style.display = 'none';
                div2.style.display = 'none';
                div3.style.display = 'flex';
                div4.style.display = 'none';
                header1.style.display = 'none';
                header2.style.display = 'none';
                header3.style.display = 'flex';
                header4.style.display = 'none';

                document.getElementById('montant_total').innerHTML = formVars['montant_total'];
                document.getElementById("ancv").addEventListener("change", function(e) {

                    displayBox = 'none';
                    if (this.checked) {

                        displayBox = 'flex';
                    }
                    document.getElementById('s_montantancv').style.display = displayBox;
                });
                document.getElementById('montantancv').addEventListener("blur", refreshAmounts);

                paiementRadios = document.getElementsByName('cheque');
                for (var i = 0; i < paiementRadios.length; i++) {

                    var self = paiementRadios[i];
                    self.addEventListener("click", function(e) {

                        items = document.getElementsByName('cheque_novembre');
                        for(i = 0;i < items.length; i++){

                            items[i].removeAttribute("required");
                        }

                        var currAmount = formVars['montant_total'];
                        if (parseInt(document.getElementById('montantancv').value)
                            && formVars['montant_total']>parseInt(document.getElementById('montantancv').value)) {

                            currAmount = formVars['montant_total']-parseInt(document.getElementById('montantancv').value);
                        }
                        switch (this.value) {

                            case '1':
                                document.getElementById('cheque_1').style.display = 'flex';
                                document.getElementById('cheque_2').style.display = 'none';
                                document.getElementById('cheque_3').style.display = 'none';
                                document.getElementById('cheque_novembre_1').value = currAmount;
                                document.getElementById('cheque_novembre_1').required = true;

                                this.checked = true;
                                document.getElementById('paiement2').checked = false;
                                document.getElementById('paiement3').checked = false;
                                document.getElementById('cheque_novembre_3').disabled = true;
                                document.getElementById('cheque_janvier_3').disabled = true;
                                document.getElementById('cheque_avril_3').disabled = true;
                                document.getElementById('cheque_novembre_2').disabled = true;
                                document.getElementById('cheque_janvier_2').disabled = true;

                                break;
                            case '2':
                                document.getElementById('cheque_1').style.display = 'none';
                                document.getElementById('cheque_2').style.display = 'flex';
                                document.getElementById('cheque_3').style.display = 'none';

                                document.getElementById('cheque_novembre_2').value = Math.floor(currAmount/2);
                                document.getElementById('cheque_janvier_2').value = Math.ceil(currAmount/2);
                                document.getElementById('cheque_novembre_2').required=true;
                                document.getElementById('cheque_janvier_2').required=true;

                                this.checked = true;
                                document.getElementById('paiement1').checked = false;
                                document.getElementById('paiement3').checked = false;
                                document.getElementById('cheque_novembre_3').disabled = true;
                                document.getElementById('cheque_janvier_3').disabled = true;
                                document.getElementById('cheque_avril_3').disabled = true;
                                document.getElementById('cheque_novembre_1').disabled = true;

                                break;
                            case '3':
                                document.getElementById('cheque_1').style.display = 'none';
                                document.getElementById('cheque_2').style.display = 'none';
                                document.getElementById('cheque_3').style.display = 'flex';

                                document.getElementById('cheque_novembre_3').value = Math.floor(currAmount/3);
                                document.getElementById('cheque_janvier_3').value = Math.floor(currAmount/3);
                                document.getElementById('cheque_avril_3').value = Math.ceil(currAmount/3);
                                document.getElementById('cheque_novembre_3').required=true;
                                document.getElementById('cheque_janvier_3').required=true;
                                document.getElementById('cheque_avril_3').required=true;

                                this.checked = true;
                                document.getElementById('paiement1').checked = false;
                                document.getElementById('paiement2').checked = false;
                                document.getElementById('cheque_novembre_1').disabled = true;
                                document.getElementById('cheque_novembre_2').disabled = true;
                                document.getElementById('cheque_janvier_2').disabled = true;

                                break;
                        }
                    });
                }
            }

            function refreshAmounts(event) {

                var newAmount = 0;
                if (formVars['montant_total']>parseInt(event.target.value)) {

                    newAmount = formVars['montant_total']-parseInt(event.target.value);
                }

                document.getElementById('cheque_novembre_1').value = newAmount;

                document.getElementById('cheque_novembre_2').value = Math.floor(newAmount/2);
                document.getElementById('cheque_janvier_2').value = Math.ceil(newAmount/2);

                document.getElementById('cheque_novembre_3').value = Math.floor(newAmount/3);
                document.getElementById('cheque_janvier_3').value = Math.floor(newAmount/3);
                document.getElementById('cheque_avril_3').value = Math.ceil(newAmount/3);

                if (formVars['montant_total']<parseInt(event.target.value)) {

                    event.target.value = formVars['montant_total'];
                }
            }
        </script>    
    </body>
</html>
